/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qugengting_image_jni_ImageUtils */

#ifndef _Included_com_qugengting_image_jni_ImageUtils
#define _Included_com_qugengting_image_jni_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qugengting_image_jni_ImageUtils
 * Method:    getImagePixels
 * Signature: (Landroid/graphics/Bitmap;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_qugengting_image_jni_ImageUtils_getImagePixels
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif


